### ISSUE TITLE
Please upload Inky 0.13.0

### ISSUE THREAD

**Issue by lofidevops** [flathub/com.inklestudios.Inky#4]
[Inky 0.13.0](https://github.com/inkle/inky/releases/tag/0.13.0) has been released. I'm not familiar with flatpak packaging, but if you can point me to some relevant docs I can try submit a PR.

**Comment by manuq** [comment]
Oh good to know about the release!

Updating the flatpak might be as easy as updating the link and hash to the Linux source here: https://github.com/flathub/com.inklestudios.Inky/blob/30489ccf2f46f59168ad6490517d6f3278ad95ff/com.inklestudios.Inky.json#L37-L38

There is also a one line patch we are applying. I hope that hasn't changed: https://github.com/flathub/com.inklestudios.Inky/blob/master/inklecate_linux.patch

And at last update the metadata. One line for the release here https://github.com/flathub/com.inklestudios.Inky/blob/30489ccf2f46f59168ad6490517d6f3278ad95ff/com.inklestudios.Inky.metainfo.xml#L25-L28

**Comment by lofidevops** [comment]
@manuq Thanks! How can I test the change (make a build?) before making the PR?

**Comment by manuq** [comment]
@lofidevops you can clone this git repository, do the changes, and then build & install locally using `flatpak-builder`. For example:
```
flatpak-builder build-dir com.inklestudios.Inky.json --force-clean --install --user --repo=repo
```

Or you can just provide a PR here and the build bot will take care of building it for you. Then you can download and test the flatpak built by the CI. See https://github.com/flathub/flathub/wiki/App-Maintenance#test-builds-and-pull-requests
