### ISSUE TITLE
Update to Inky 0.14.1

### ISSUE THREAD

**Issue by tfranken90** [flathub/com.inklestudios.Inky#6]
[Inky 0.14.1](https://github.com/inkle/inky/releases/tag/0.14.1) has been released.

**Comment by Zishan-Rahman** [comment]
> [Inky 0.14.1](https://github.com/inkle/inky/releases/tag/0.14.1) has been released.

@tfranken90 (I apologise for the ping) I just created a PR that addresses your issue here: #7. You should be able to close this issue once the PR is merged.

In the meantime, you can try out the test build [here](https://github.com/flathub/com.inklestudios.Inky/pull/7#issuecomment-1522382280).

**Comment by manuq** [comment]
No need to apoligize, on the contrary, thank you very much @Zishan-Rahman !
